server:
  port: 9000
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 903238603946-3291rnl4i6cmmcoigv6vaa2g0s741f43.apps.googleusercontent.com
            client-secret: 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
            scope: openid,profile,email
    main:
      allow-circular-references: true

  h2:
    console:
      enabled: true
      settings:
        trace: false
logging:
  level:
    org: info
    com: off
---
spring:
  profiles:
    active: local
---
spring:
  sql:
    init:
      mode: always
      data-locations: classpath:data-h2.sql
      schema-locations: classpath:schema-h2.sql
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      id:
        new_generator_mappings: true
      ddl-auto: none
  config:
    activate:
      on-profile: local
---
spring:
  sql:
    init:
      mode: always
      schema-locations: classpath:hr_schema_postgres.sql
      data-locations: classpath:hr_data_postgres.sql
  datasource:
    url: jdbc:postgresql://dumbo.db.elephantsql.com:5432/ocogthjb

    username: ocogthjb
    password: jEwJ0fjbjtONJ1Os6qRAO-huwBbe8Hgg
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: false
  config:
    activate:
      on-profile: prod
