server:
  port: 9000
spring:
  h2:
    console:
      enabled: true
      settings:
        trace: false
logging:
  level:
    org:
#      hibernate: debug
---
spring:
  profiles:
    active: dev #dev
---
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    properties:
      generate_ststistics: true
    generate-ddl: true
  config:
    activate:
      on-profile: dev
---
spring:
  sql:
    init:
      mode: never
      schema-locations: classpath:hr_schema_postgres.sql
  datasource:
    url: jdbc:postgresql://localhost:5432/
    username: postgres
    password: postgres
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        generate_statistics: false
    show-sql: true
  config:
    activate:
      on-profile: prod
welcome:
  message: welcome
